//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSA_MOTOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string To_Name { get; set; }
        public string To_Phone { get; set; }
        public string Ship_Name { get; set; }
        public string Ship_Company { get; set; }
        public string Ship_Adress { get; set; }
        public string Ship_City { get; set; }
        public string Ship_Contact { get; set; }
        public Nullable<int> Vehicle_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<System.DateTime> Delivary_Date { get; set; }
        public string Payment_Terms { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
