//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSA_MOTOR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuotationDbContext : DbContext
    {
        public QuotationDbContext()
            : base("name=QuotationDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<quotation> quotations { get; set; }
        public virtual DbSet<Administration> Administrations { get; set; }

        public System.Data.Entity.DbSet<BusinessLayer.PartsInventory> PartsInventories { get; set; }
    }
}
